//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy_Football
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Name { get; set; }
        public string Position { get; set; }
        public string Team { get; set; }
        public double ProjectedPoints { get; set; }
        public double Price { get; set; }
    }
}
